### PR TITLE
Settings ex import

### PR DESCRIPTION
**Pull request by AdrianLxM**
This is @jamorham 's im-/export functionallity (https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/266) with some small changes:
- export settings to a subdirectory of the one we use for csv and database exports
- no recursive deletion of the export directory
- added Nav-Drawer to the Import/Export-Activity instead of floating close button
- adopted Import/Export-Activity to small screens
- grouped all export/import items in the menu

### CODE REVIEW

**Comment by jamorham** [comment]
This looks good to me. `ScrollView` is a good addition, menu layout looks sensible to integrate with existing import/export features and consistent directory path with `getExternalDir()`.

**Comment by tzachi-dar** [comment]
Nice job jamorham and AdrianLxM.

2 things that I think need to be changed:

1) "Settings to external storage". I think it needs to show that is also "Settings from external storage". Not sure if this can be done given the limited space.

2) This activity works on the file /sdcard/xdrip/settingsExport.
Since people might use this to pass xDrip from phone to phone, I believe that the text should mention this file location.
For example: "The settings will be stored/restored from the directory "/sdcard/xdrip/settingsExport.  Please make sure it is there before restoring".

Also when setting, the text used is sdcard'/xdrip/SettingsExport'. This should be '/sdcard/xdrip/SettingsExport'

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
@tzachi-dar 

ad 1) you click "Im/Export..." and then "Settings to external storage" we could make that:
 "Im/Export..." and then "Im/Export Settings"

ad 2 and 3) It actually works on the same external storage directory where the databases (and logcats?) are exported to. So "sdcard" is not necessarily part of the path.
On modern phones (that we all use) there always is an external storage - if not an sdcard it will be the built in external storage. Just some Android distros allow to restrict the access - but then the user knows what he is doing.

But actually I don't care much what the text says: Just tell me what you would like and I'll put it ;)

**Comment by tzachi-dar** [comment]
As for (1) go with it :-)

As for 2, please add:
"The settings will be stored/restored from the directory '" + getCustomSDcardpath() +  "' +/sdcard/xdrip/settingsExport. Please make sure it is there before restoring".

As for 3, please replace:
toast("Preferences saved in sdcard '/xdrip/settingsExport' ");
toast("Preferences saved in ' " + getCustomSDcardpath() +" ' " ); // remove the spaces, I have added a space between ' and " because otherwise it is unreadable

**Comment by AdrianLxM** [comment]
I think that something like "/storage/emultated/0/xdrip/settingsExport" will confuse people as most android file managers won't show it like this. Neither does it show like this when connecting to a PC via data cable.
But ok, I'll put it like this - people will ask of Facebook anyways.

**Comment by tzachi-dar** [comment]
I believe that if this is what it will be showing, than don't change what you have...

**Comment by AdrianLxM** [comment]
Ok, I updated the menu names.
Also added the directory path to the "could not open..." toast.

**Pull request merged**
