### PR TITLE
Zip Export

### PR DESCRIPTION
**Pull request by AdrianLxM**
... my 14.4MB database gets compressed to 5.8MB.

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
Sweet, Im going to give this a shot

**Comment by StephenBlackWasAlreadyTaken** [comment]
Works perfectly for me!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Tested on a few more devices, I say this looks good to merge to me

**Comment by AdrianLxM** [comment]
Fine, thanks @StephenBlackWasAlreadyTaken. Merging...

**Pull request merged**
