### PR TITLE
G5 fixes2

### PR DESCRIPTION
**Pull request by AdrianLxM**
This atm is Alpha 8.1

### CODE REVIEW

**Comment by M1Sports20** [comment]
Hello, I have been testing this and have had worse syncing problems than branch g5_fixes.  Just an FYI.

**Comment by AdrianLxM** [comment]
@M1Sports20 was the difference between Alpha 8 and Alpha 8.1?

**Comment by M1Sports20** [comment]
I don't see versions

commit  185e3d8 works a lot better than 0c270d9

Let me know if you need any support. development or anything.  I just found these projects and am looking them over.

**Comment by AdrianLxM** [comment]
@M1Sports20, As you sound like you could pull logcats from Android, you could/should join "xDrip G5 closed testing" on facebook (I know facebook :/ , but it's the best way to reach the users)
https://www.facebook.com/groups/1021594524580709/?fref=nf

**Comment by chrisprad** [comment]
I'm a developer and have been playing with this branch over the weekend as well. Communication is pretty wonky on my Nexus 6 on the newest OTA with Marshmallow. I've got readings, but with heavy gaps and multiple resets/redeployments required. I'll try commit 185e3d8 shortly. 

I tried to join the facebook group, but it's still left in the "Pending" state after a few days.

**Comment by victorkp** [comment]
Been using for two weeks on Nexus 6P, Android N dev preview 3, with quite good results.

Also Pending on Facebook Group.

**Comment by Mondelman** [comment]
Still pending to be authorized for testing G5 and MotoG3. 
Hope it can be done before weekend, it's perfect time for me as I have some spare time...

**Comment by chrisprt** [comment]
@Mondelman If you identify a build that you'd like to try (release, commit, whatever) I'd be happy to build it for you. I've been pending for months on FB with no response.

**Comment by Mondelman** [comment]
It works ok in my G3, though some instability when wifi is on.
I'd like to have sort of notebook in the program, just to keep track of carbs and insulin bolus.
Many thanks, @chrisprt

**Comment by chrisprt** [comment]
@Mondelman That's good. Another huge problem (I believe) I have is interference from the Receiver or other 2.4ghz devices. BLE seems to be especially fickle, and the android stack isn't stellar either.

**Comment by Mondelman** [comment]
Once running, I can switch iPhone Bluetooth on and no interference, at least in my case.
Keep you updated with any further comments.
BR

**Pull request closed without merging**
