### PR TITLE
Bgreadings shortcut

### PR DESCRIPTION
**Pull request by AdrianLxM**
Will add a preference that puts a shortcut to SpeakReadings in the menu.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
How comes this is done in the file home.java while others are being done in navdrawbuilder? I believe that this should all be in the same place.
See: 

```
    if (prefs.getBoolean("show_data_tables", false)) {
        this.nav_drawer_options.add("BG Data Table");
        this.nav_drawer_intents.add(new Intent(context, BgReadingTable.class));
        this.nav_drawer_options.add("Calibration Data Table");
        this.nav_drawer_intents.add(new Intent(context, CalibrationDataTable.class));
    }
```

**Comment by tzachi-dar** [comment]
OK, read the code again and I now understand why there is a difference.
This looks good to me.

**Comment by AdrianLxM** [comment]
Thanks @tzachi-dar

**Comment by ghost** [comment]
Thanks for merging this great feature!

**Pull request merged**
