### PR TITLE
DB Import

### PR DESCRIPTION
**Pull request by AdrianLxM**
This is my version of the DB-Import:
tired of writing text, here are the hopefully self-explanatory screenshots:
screenshot_2015-08-27-15-41-29 screenshot_2015-08-27-15-41-36
screenshot_2015-08-27-15-41-52 screenshot_2015-08-27-15-42-02
screenshot_2015-08-27-15-42-38 screenshot_2015-08-27-15-42-10
screenshot_2015-08-27-15-42-15 screenshot_2015-08-27-15-42-21

Tested on my device:
- Import database
- Try to import old database with different db schema/version -> import correctly rejected
- Imported database extracted from zip in subfolder
- Import db exported as automatic backup from last import
- renamed/deleted directory 'xdrip' -> generated directory for the user to find + message "No databases found"
- empty directory 'xdrip' -> message "No databases found"
- Try to import some other file (textfile) renamed to *.sqlite -> Correct message "Database connot be opened... aborting".

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Now also tested it on my ZGPAX S8 Android 4.4 wrist watch:
Import works and all dialogues are visible. I wouldn't have believed it before testing :)

**Comment by StephenBlackWasAlreadyTaken** [comment]
Tested on my nexus 7 and my old lg, now they all have the same database, yay!!

**Comment by AdrianLxM** [comment]
Super.
@ceben80 tested it as well and it worked on a Sony xperia E1.

**Comment by ghost** [comment]
Yes...confirm from my side! 
How often I have redefined personal settings (e.g. extensive alarm settings), which must now not be made...great!

Cheers,
Matthias

**Comment by StephenBlackWasAlreadyTaken** [comment]
I say merge this guy in!! No issues after plenty of testing!

**Comment by AdrianLxM** [comment]
Thanks for testing

**Pull request merged**
