### PR TITLE
don't crash and burn when making toasts for CSV/database exports

### PR DESCRIPTION
**Pull request by mgranberry**
A bigger problem is that none of the Toasts around errors will actually work (they will crash the app instead).  Should probably be fixed in another PR.

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Let me guess, I forgot to run them on the UI-Thread? :facepalm:

**Comment by mgranberry** [comment]
yep.  The road to hell is paved with good intentions.  It looks like posting a toast-creating runnable to the main looper is an easy out for these.

**Comment by AdrianLxM** [comment]
Tested making toast (by causing an error on purpose) and it works great, thanks.

**Comment by AdrianLxM** [comment]
The other changes also look very reasonable to me. I think we can merge this.

**Pull request merged**
