### PR TITLE
Pebble notification with timestamp

### PR DESCRIPTION
**Pull request by tanja3981**
Added timestamp to notification message to avoid the pebbles prevent "duplicate" notifications on BG alarms.

### CODE REVIEW

**Comment by jstevensog** [comment]
Fantastic. I have wanted to do this for ages.
Thank you very much.
Cheers

---- Tanja wrote ----

**Comment by AdrianLxM** [comment]
@tanja3981, aparently some unrelated changes you did came through as well. Like the watchfaces, settings, ...

Could you please remove them from this PR? Thanks.

**Comment by tanja3981** [comment]
deleted pull requests and created a new one with a clean branch.

**Comment by AdrianLxM** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/350

**Pull request closed without merging**
