### PR TITLE
remove default creation of low alert 55 and allow modification or del…

### PR DESCRIPTION
**Pull request by JohanDegraeve**
…etion existing alert of this type

This is rather annoying that this type of alert can not be deleted or modified. Creation of it also makes no sense as there's already one created at 70.

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
just noticed this on fb https://www.facebook.com/groups/cgminthecloud/permalink/857617827692808/

**Comment by AdrianLxM** [comment]
I now too see the usecase for deleting the 55mg/dl alert:

If you use Share as input and want to use the more sophisticated alarms in xDrip you will have the case of the Share receiver alarming at 55 (unchangable) and xDrip alarming at the same time.

In case of a severe hypo in a public silent place like a library/classroom, ... having to disable 2 alarms on different devices while treating the hypo might actually be quite stressful.

**Comment by JohanDegraeve** [comment]
well not only in combination with Share i think.
It can sometimes take time before sensor values are up again although real blood glucose values are high enough to continue. Also the silent mode override can not be disabled. 
It could be for example that I've seen just a few minutes or longer before I was getting low and took carbs, so I don't need the alert or certainly don't want to be in a situation where it starts making noise. The only thing I could do is disable low alerts for a period, or pre-snooze that specific alert, but then I need to think about, open the app etc..

**Comment by jstevensog** [comment]
Agreed.  I believe the unchangeable alert should be changeable, at least to some degree.  Either the ability to make it NOT override silent mode, or set time ranges.  I know why it is there, but I never liked itbon the Dex either.

---- Johan Degraeve wrote ----

**Pull request closed without merging**
