### PR TITLE
Status for happ

### PR DESCRIPTION
**Pull request by AdrianLxM**
This will add a status field to the wear watchfaces that HAPP can broadcast it's status to.

### CODE REVIEW

**Comment by AdrianLxM** [comment]
screen-status

**Comment by timomer** [comment]
Working perfectly well for me, have been using this solid for the last few months, I know other HAPP users are too.

Would be cool to get this into master to take advantage of other xDrip improvement's

**Comment by AdrianLxM** [comment]
Yea, I'd really like to merge this now.
Thanks Tim for the comment and for testing.

Any more comments?

**Comment by tzachi-dar** [comment]
Seems reasonable to me although I did not read the wear part thoroughly.

**Comment by timomer** [comment]
yay! Great, can finally update xDrip ;)

**Comment by timomer** [comment]
fyi - this is all working fine for me

**Pull request merged**
