### PR TITLE
In xbridge battery level = 0, then don't show the red status message …

### PR DESCRIPTION
**Pull request by JohanDegraeve**
…in home screen saying 'waiting for packet'
- I'm using an xdrip with xbridge software installed, but without the resistor wiring
  As a consequence, batterylevel is always 0, but I always see on the Home screen in red "waiting for packet"
  So I removed that : if batterylevel = 0 then don't show that message at all. For an xBridge that has the wiring, I assume battery level should never be 0 or it's dead.

Moreover, it looks a strange message "waiting for package ?"

### CODE REVIEW

**Comment by jstevensog** [comment]
I believe this would be best as a setting.  The idea of the message was to
indicate that the battery level could not be determined until the first
packet was received.  So, a setting to either show or not show this message
when xBridge is being used to collect the data would be preferable to
removing the message altogether.
Cheers

On Tue, Nov 24, 2015 at 9:57 AM, Johan Degraeve notifications@github.com
wrote:

> …in home screen saying 'waiting for packet'
> - I'm using an xdrip with xbridge software installed, but without the
>   resistor wiring As a consequence, batterylevel is always 0, but I always
>   see on the Home screen in red "waiting for packet" So I removed that : if
>   batterylevel = 0 then don't show that message at all. For an xBridge that
>   has the wiring, I assume battery level should never be 0 or it's dead.
> 
> ## Moreover, it looks a strange message "waiting for package ?"
> 
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181
> Commit Summary
> - In xbridge battery level = 0, then don't show the red status message
>   in home screen saying 'waiting for packet'
> 
> File Changes
> - _M_ app/src/main/java/com/eveningoutpost/dexdrip/Home.java
>   https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181/files#diff-0
>   (8)
> 
> Patch Links:
> 
>    -
>    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181.patch
>    -
>    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by JohanDegraeve** [comment]
alternative is that we have indeed a setting which is set to "true" as soon as there's one reception of a packet with battery_level > 0 ?
true means message is shown

the less user settings the better

**Comment by AdrianLxM** [comment]
How about the xBridge frimware, when it detects the classic circuit, sends a code that can be interpreted as "no battery value present"?

But a persistent flag (be it in settings or the db*) that gets reset on bt scan should also work.

`\* I prefer the db as changing the settings may trigger a lot of listeners to setting changes, but the xBridge-battery-level also updates the setting with every reading without much lag - so practically it won't be a problem either.

**Comment by tzachi-dar** [comment]
Adrian idea can only be implemented on new fw. so, probably on xBridge3.

John, do you see a real scenario that battery will be sent as 0? (while
resistors are on and everything else works)?
Thanks
Tzachi

**Comment by jstevensog** [comment]
Battery should never be 0, which is why I chose it as the value to indicate
that no packet had been received from the bridge when first flashed and
xDrip newly started.  I am happy enough to remove the red "Waiting for
Packet" message, as long as the 0% somehow indicates something other than
normal.

My preference is for a setting that only appears when xBridge is set (Like
the Transmitter ID setting), that allows xDrip to display/not display
battery percentage.  The reason being, people like Johan and others do
other things with the wixel to power it.  Those people, who do not need to
know what the battery capacity is, can just turn it off.

I have had people power the bridge from a phone so it is always 100%, and
others that do not power it from batteries at all.  So being able to turn
the percentage indication on/off is good.  This setting can also be used
with the pebble support to either send the battery level or not.

So, to me, a setting is the best way to go to support all scenarios.  I
will try an implementation in my new Pebble code branch, and if it works
OK, I will create a separate branch and people can see what they think.

Cheers

On Wed, Nov 25, 2015 at 1:24 AM, tzachi-dar notifications@github.com
wrote:

> Adrian idea can only be implemented on new fw. so, probably on xBridge3.
> 
> John, do you see a real scenario that battery will be sent as 0? (while
> resistors are on and everything else works)?
> Thanks
> Tzachi
> 
> On Tue, Nov 24, 2015 at 1:31 PM, AdrianLxM notifications@github.com
> wrote:
> 
> > How about the xBridge frimware, when it detects the classic circuit,
> > sends
> > a code that can be interpreted as "no battery value present"?
> > 
> > But a persistent flag (be it in settings or the db*) that gets reset on
> > bt
> > scan should also work.
> > 
> > `\* I prefer the db as changing the settings may trigger a lot of
> > listeners
> > to setting changes, but the xBridge-battery-level also updates the
> > setting
> > with every reading without much lag - so practically it won't be a
> > problem
> > either.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181#issuecomment-159237251
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181#issuecomment-159281739
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by jstevensog** [comment]
Actually, originally the battery percentage was always only in memory.
That way whenever xDrip started up, this message would appear telling you
that it had not yet received a xBridge2 packet with the battery percentage
in it.  It made a lot more sense back then, as it was also a clear
indication not to pay attention to the last BG reading as well.

Since the battery percentage was moved from memory to a "setting", this
doesn't happen any more, and the message has lost it's meaning.  Probably
more of a reason why I should create an xBridge collection service.
Especially as xBridge3 protocol will complicate things in the
DexCollectionService.  I'll think all that through and get it done soon.

So, I guess what I am saying is, get rid of "Waiting for Packet" message if
everyone agrees, but make the display of the battery percentage a setting
that only appears if xBridge is set as a data source, but displaying it is
the default value.  That way people hacking xBridge into different styles
of circuits can choose to display or not display it as they need.
Cheers

On Wed, Nov 25, 2015 at 9:58 AM, John Stevens jstevensog@gmail.com wrote:

> Battery should never be 0, which is why I chose it as the value to
> indicate that no packet had been received from the bridge when first
> flashed and xDrip newly started.  I am happy enough to remove the red
> "Waiting for Packet" message, as long as the 0% somehow indicates something
> other than normal.
> 
> My preference is for a setting that only appears when xBridge is set (Like
> the Transmitter ID setting), that allows xDrip to display/not display
> battery percentage.  The reason being, people like Johan and others do
> other things with the wixel to power it.  Those people, who do not need to
> know what the battery capacity is, can just turn it off.
> 
> I have had people power the bridge from a phone so it is always 100%, and
> others that do not power it from batteries at all.  So being able to turn
> the percentage indication on/off is good.  This setting can also be used
> with the pebble support to either send the battery level or not.
> 
> So, to me, a setting is the best way to go to support all scenarios.  I
> will try an implementation in my new Pebble code branch, and if it works
> OK, I will create a separate branch and people can see what they think.
> 
> Cheers
> 
> On Wed, Nov 25, 2015 at 1:24 AM, tzachi-dar notifications@github.com
> wrote:
> 
> > Adrian idea can only be implemented on new fw. so, probably on xBridge3.
> > 
> > John, do you see a real scenario that battery will be sent as 0? (while
> > resistors are on and everything else works)?
> > Thanks
> > Tzachi
> > 
> > On Tue, Nov 24, 2015 at 1:31 PM, AdrianLxM notifications@github.com
> > wrote:
> > 
> > > How about the xBridge frimware, when it detects the classic circuit,
> > > sends
> > > a code that can be interpreted as "no battery value present"?
> > > 
> > > But a persistent flag (be it in settings or the db*) that gets reset on
> > > bt
> > > scan should also work.
> > > 
> > > `\* I prefer the db as changing the settings may trigger a lot of
> > > listeners
> > > to setting changes, but the xBridge-battery-level also updates the
> > > setting
> > > with every reading without much lag - so practically it won't be a
> > > problem
> > > either.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181#issuecomment-159237251
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181#issuecomment-159281739
> > .
> 
> ## 
> 
> John Stevens
> "You are how you live, not what you have."

## 

John Stevens
"You are how you live, not what you have."

**Comment by JohanDegraeve** [comment]
sounds ok to me

**Comment by JohanDegraeve** [comment]
although, why would someone still install to xdrip software ? 
I installed https://raw.githubusercontent.com/jstevensog/wixel-sdk/master/apps/xBridge2/xBridge2.wxl
and when scanning for bluetooth, the device is named xbridge. When selecting it it's automatically configured as an xbridge.
The big advantage here off course is that the transmitter code can be set via the app.

I would think it's better to replace all the install instructions (the youtube xDrip (formerly Dexdrip) Wixel Install Instruction Video is not even necessary anymore)  and just expose this xbridge2 version to anyone.

**Comment by jstevensog** [comment]
Yeah, that is not my call.  That is something for us all to decide and
agree to.
The code is available to anyone, but obviously they need a link to it.
Cheers

On Wed, Nov 25, 2015 at 6:50 PM, Johan Degraeve notifications@github.com
wrote:

> although, why would someone still install to xdrip software ?
> I installed
> https://raw.githubusercontent.com/jstevensog/wixel-sdk/master/apps/xBridge2/xBridge2.wxl
> and when scanning for bluetooth, the device is named xbridge. When
> selecting it it's automatically configured as an xbridge.
> The big advantage here off course is that the transmitter code can be set
> via the app.
> 
> I would think it's better to replace all the install instructions (the
> youtube xDrip (formerly Dexdrip) Wixel Install Instruction Video is not
> even necessary anymore) and just expose this xbridge2 version to anyone.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/181#issuecomment-159527367
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by JohanDegraeve** [comment]
I noticed that default text is shown until double calibration is done.
The default text was 100%
I changed that to "Bridge Battery level unknown"

In this implementation : At initial start, the message will say "Bridge Battery level unknown" up to the moment where the double calibration is done.
As soon as double calibration is done, if battery level = 0, then it will not be displayed at all, if battery level > 0, it will be displayed.

Better would be that the bridge battery level is shown as soon as the first reading is received , which should take maximum 5 minutes - but I don't know where in the code to change that

**Comment by jstevensog** [comment]
Agreed with the bridge battery being shown as soon as a data packet is received from xBridge.  That is how it works on the Pebble.  Would be good for the functionality to match.  Been trying to achieve common data across home/widget/Pebble.
Cheers

---- Johan Degraeve wrote ----

**Comment by JohanDegraeve** [comment]
Does someone still have a proposal here ? or do I close this pull request ?

**Comment by jstevensog** [comment]
I will need to check, but I am pretty sure the xBridgeImprovements branch merged a few days ago included the ability to turn off the bridge battery display if xBridge is the selected data source.  It is in the current xDrip I am running, which is current master (as at 0900 +11 GMT 8 Dec) with PebbleTrend merged.

It is probably better for the cases of no resistors for battery monitoring, or permanently powered bridges (from phone).  I'll check in the morning to make sure if it is in master now or I have mistakenly put it on PebbleTrend.
Cheers

---- Johan Degraeve wrote ----

**Comment by jstevensog** [comment]
OK, I was stupid and put this into PebbleTrend branch.  I will create a new branch that adds this logic to Preferences and Home today, and make a PR for comment.
Cheers

---- Johan Degraeve wrote ----

**Comment by JohanDegraeve** [comment]
see pull request #209

**Pull request closed without merging**
