### PR TITLE
Add timestamp to avoid pebble duplicate detection for BG alarms.

### PR DESCRIPTION
**Pull request by tanja3981**

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Looks pretty straight foreward to me. I think we can merge this quickly.
Danke @tanja3981.

BTW does the same thing (deduping by pebble) happen with missed reading alerts?

**Comment by tanja3981** [comment]
I'm not using those, so I haven't tried. ;-)
The code change is for BG alerts only, so I guess I should add it there, too.

**Comment by tzachi-dar** [comment]
Seems good to me.

**Comment by tanja3981** [comment]
I added the time for the other notifications (calibration, signal lost, bg rise/fall), too.
Should be fine now.

**Comment by AdrianLxM** [comment]
Danke @tanja3981

**Pull request merged**
