### PR TITLE
Fixes for xBridge Prompt

### PR DESCRIPTION
**Pull request by AdrianLxM**
- Remove barcode scanner for share from xBridge prompt
- Make txid uppercase

Please comment.

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
We dont want to allow scanning?

**Comment by AdrianLxM** [comment]
As far as I see it, there is no scanning for xBridge.
There wasn't even an onClickListener registered.

Also as far as I remember (not having Share), the barcode on the Share receiver is the serial number, not the transmitterID. So scanning would just be for Share, not for xBridge.

**Comment by StephenBlackWasAlreadyTaken** [comment]
I believe @mgranberry added it for scanning the transmitter box

**Comment by AdrianLxM** [comment]
Hm, I thought this was just reuse of the code/layout. The button was not active so for beta4 or release something should be changed?
What was your intention @mgranberry?

**Comment by mgranberry** [comment]
Yes.  It was for scanning the transmitter box, but the serial number format was complex enough that I didn't want to do anything with it until I was able to look at a non-US box.  Removing it is probably the correct thing to do.

**Comment by AdrianLxM** [comment]
Except from making it all caps on entering the code to avoid wrong user input, the button is just hidden with `dialog.findViewById(R.id.scannerButton).setVisibility(View.GONE);` but still present in the layout.

I can send you, @mgranberry, the photo of a German box tomorrow, if you like.

**Comment by AdrianLxM** [comment]
I'll merge this - it just hides the button- easily undoable once it actually scans something.
Making it all caps I think should be in.

**Pull request merged**
