### PR TITLE
Make sure that check for duplicate packets happens under the lock and…

### PR DESCRIPTION
**Pull request by tzachi-dar**
… for all devices.

Signed-off-by: Tzachi Dar tzachi.dar@gmail.com

This influances xDrip and xBridge, so please look carefully.

### CODE REVIEW

**Comment by jstevensog** [comment]
I don't see any issue for xBridge in here, but I will run it up in the next
couple of days and try it out to be sure.
Thanks Tzachi.
Cheers

On Sun, Dec 6, 2015 at 10:24 AM, tzachi-dar notifications@github.com
wrote:

> … for all devices.
> 
> Signed-off-by: Tzachi Dar tzachi.dar@gmail.com
> 
> ## This influances xDrip and xBridge, so please look carefully.
> 
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203
> Commit Summary
> - Make sure that check for duplicate packets happens under the lock
>   and for all devices.
> 
> File Changes
> - _M_
>   app/src/main/java/com/eveningoutpost/dexdrip/Models/TransmitterData.java
>   https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203/files#diff-0
>   (26)
> 
> Patch Links:
> 
>    -
>    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203.patch
>    -
>    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by jstevensog** [comment]
Hi Tzachi,
I have run up your duplicates-lock branch merged into my local test branch
(master from yesterday with PebbleTrend branch) and am running it
successfully with xBridge.  Only been a short time, but I am not seeing
anything alarming, and really don't expect to
If I don't report any problems to you by the end of 9th of December, I
suggest you merge this before it gets too stale.  Again, nice work.
Cheers

On Mon, Dec 7, 2015 at 9:49 AM, John Stevens jstevensog@gmail.com wrote:

> I don't see any issue for xBridge in here, but I will run it up in the
> next couple of days and try it out to be sure.
> Thanks Tzachi.
> Cheers
> 
> On Sun, Dec 6, 2015 at 10:24 AM, tzachi-dar notifications@github.com
> wrote:
> 
> > … for all devices.
> > 
> > Signed-off-by: Tzachi Dar tzachi.dar@gmail.com
> > 
> > ## This influances xDrip and xBridge, so please look carefully.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203
> > Commit Summary
> > - Make sure that check for duplicate packets happens under the lock
> >   and for all devices.
> > 
> > File Changes
> > - _M_
> >   app/src/main/java/com/eveningoutpost/dexdrip/Models/TransmitterData.java
> >   https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203/files#diff-0
> >   (26)
> > 
> > Patch Links:
> > 
> >    -
> >    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203.patch
> >    -
> >    https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/203
> > .
> 
> ## 
> 
> John Stevens
> "You are how you live, not what you have."

## 

John Stevens
"You are how you live, not what you have."

**Comment by tzachi-dar** [comment]
OK, I'm waiting a couple of more days.

**Comment by jstevensog** [comment]
Actually, don't wait on my account.  It has worked fine all afternoon and evening.  Merge when ready from an xBridge point of view.
Cheers

---- tzachi-dar wrote ----

**Comment by tzachi-dar** [comment]
OK,
Thanks for testing this.

**Pull request merged**
