### PR TITLE
X drip viewer8

### PR DESCRIPTION
**Pull request by tzachi-dar**
This is the xDripViewer rebased on the current master.

It also changes the labels for the watch.

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Compiling this on my system does not include the wear-release.
It isn't even created.

**Comment by tzachi-dar** [comment]
On my system, ./wear/build/outputs/apk/wear-release-unsigned.apk was created.
Are you looking for another thing?

**Comment by tzachi-dar** [comment]
actually, this is an old file, looking at it more deeply.

**Comment by AdrianLxM** [comment]
It has to be signed... I think I can find a fix by propagating the configuration in the dependency to the wear app.

**Comment by tzachi-dar** [comment]
I believe that signing, can also be done later by the following steps:

follow: http://developer.android.com/tools/publishing/app-signing.html

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /usr/local/google/home/tzachi/Downloads/signed_apk_keystore_copy.jks  ./app/build/outputs/apk/app-xDrip-release-unsigned.apk xDrip

jarsigner -verify -verbose -certs ./app/build/outputs/apk/app-xDrip-release-unsigned.apk

/usr/local/google/home/tzachi/AndroidSDK/android-sdk-linux/build-tools/22.0.1/zipalign -v 4 ./app/build/outputs/apk/app-xDrip-release-unsigned.apk ./app/build/outputs/apk/app-xDrip-release.apk

Or is it another type of signing?

**Comment by AdrianLxM** [comment]
Well, if you sign the wear-app later, you have to repack the app-release to include the wear.apk and resign it again. This is a lot of work.
Better to find a solution where it is done automatically.

**Comment by tzachi-dar** [comment]
But to sign it in the process, I have to do something like:
signingConfigs {
        release {
            storeFile file("myreleasekey.keystore")
            storePassword "password"
            keyAlias "MyReleaseKey"
            keyPassword "password"
        }
    }

and than I have to expose the passwords.
But is this what you mean?

**Comment by AdrianLxM** [comment]
No, it should be a simple rewrite of the dependency including passing of the configuration parameter.
I will update the build.gradle in a few minutes.

I will have to de-capitalize the names of the flavours for that to work.

**Comment by tzachi-dar** [comment]
OK, thanks.

**Comment by AdrianLxM** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/294
This should do it.

**Comment by tzachi-dar** [comment]
OK, thanks.

**Comment by AdrianLxM** [comment]
When compiled as "xDripViewer", the settings section "Data Sync" (where you usually upload things) is empty but the section is still there.

**Comment by AdrianLxM** [comment]
It would be great if this could also be automatically renamed to "XDripViewer settings":
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/blob/xDripViewer8/wear/src/main/res/xml/preferences.xml#L4

**Comment by AdrianLxM** [comment]
At the moment exports form xDrip and xDrip-Viewer go to the same directory and maybe even overwrite themselves (in case of settings-export). In would be nice if you could conditionally change this string
(https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/blob/xDripViewer8/app/src/main/java/com/eveningoutpost/dexdrip/utils/FileUtils.java#L17) to "./xdripviewer".

**Comment by AdrianLxM** [comment]
The Android-Wear integration now works perfectly fine with the NS account you provided.
Even when the hundreds of values come in after initialization: The arrow dances a bit and the "minutes ago" count down - but everything runs smoothly on the watch :+1: 

Also when having installed both xDripViewer and xDrip on the same phone, you can simply toggle the watchfaces from xDrip to xDripViewer and back.

In the next couple of days I hope I can test this with data produced from the medtronic uploader thanks to @MosiGithub.

**Comment by tzachi-dar** [comment]
I'll try to fix the points that you have raised, most of them should not be that complicated.

As for testing with the medtronic uploader, I'm not that optemisitc. The current code is looking at fields that are only uploaded when xDrip is at xDripviewer upload mode. Will they have such fields?

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
Well, at least it should not crash (as people may have disabled xDripViewer upload mode)... so I can test that.

By the way: I've been running xDrip (flavour) compiled from this PR and it works as it is supposed to. No noticable difference to xDrip prior to that :+1: :)

**Comment by tzachi-dar** [comment]
Sure, you can test that there are no crashes. I guess that next steps are indeed to test it with other uploaders. I would start with the "classic nightscout uploader" first.

**Comment by tzachi-dar** [comment]
As for settings. The file name for the viewer will be:
com.eveningoutpost.dexdrip.viewer_preferences.xml

So, should I change the directory, or is changing the filename alone enough?

**Comment by AdrianLxM** [comment]
It should be a different directory. Databas export would still look the same - and then possibly be imported to the wrong programme. Changing the directory makes xdrip or xdripviewer search in just their directory for imports.

**Comment by tzachi-dar** [comment]
ok, I'll fix that with a different directory.

**Comment by tzachi-dar** [comment]
Committed a fix for different file name and directory for xDrip and xDripViewer.
Also changed settings on the watch.

**Comment by tzachi-dar** [comment]
as for the "Data Sync" not appearing in the xDripViewer.
I can obviously remove it, but this will have a price in code. This will need a lot more if statements.
So I thought that I'll change that on the viewer to be something like "No data sync" or maybe change that to "".

Thoughts?

**Comment by AdrianLxM** [comment]
If it is so much easier take "". I'd say. This will give us a double delimiter and doesn't look bad either.

**Comment by tzachi-dar** [comment]
OK, fixed the datasync issue.

**Comment by tzachi-dar** [comment]
Added support for xDripViewer even when xDrip itself is not in xDripViewer mode.

**Comment by tzachi-dar** [comment]
If anyone has more comments please let me know.

**Comment by tzachi-dar** [comment]
Closing this branch since it was merged in xDripViewer 8.

**Pull request closed without merging**
