### PR TITLE
Alerts times6

### PR DESCRIPTION
**Pull request by tzachi-dar**
This is a fix for the alerts timing issues based on the last discussions we had.
I'm running with this for a successful day so far.

Please note that I'll be with very little mail access in the coming days.

### CODE REVIEW

**Comment by AdrianLxM** [comment]
I forgot to test this, but can't this mess with the reraise interval when a new value comes in?

**Comment by tzachi-dar** [comment]
It should not have any influence on reraised alerts:
The real change in this function is under the code in the function: calcuatleArmTime
In this function, if (activeBgAlert != null) (that is, there is an active alert...) we use the same value as before. Only if this value is negative, we set it to one more minute, so it will probably not create any issues with existing alerts.

**Comment by AdrianLxM** [comment]
Well, what if we reraise every minute, but the system gets triggered a few seconds earlier due to a new value e.g. Than the next alert sound gets stalled by almost a minute because of `if (wakeTime < now + 60000) {...`.

**Comment by tzachi-dar** [comment]
you are probably right, we should probably replace
if (wakeTime < now + 60000) {
with
if (wakeTime < now)

will that solve the issue?

**Comment by AdrianLxM** [comment]
> quoting @tzachi-dar:
> `if (wakeTime < now) ...`

Yes, that's what I was thinking of and this should solve the issue.

It might not be much of an issue at all... only if you don't acknowledge the alarm within 5 minutes or if you just work with large reraise intervals and expect it to be exact. (E.g. reraise value of 30 minutes and it will actually reraise at 31 minutes).
It is more a thing that it could be noticeable to the users and make them loose trust in the alarm system.

**Pull request merged**
