### PR TITLE
xDrip 2 beta

### PR DESCRIPTION
**Pull request by StephenBlackWasAlreadyTaken**
Time to come out of beta?

### CODE REVIEW

**Comment by stavlor** [comment]
:+1: been working well for me

**Comment by tzachi-dar** [comment]
Code is working well.
We might want to also have the checkin that collects sensor information.
It is already writen, but needs some wording refignments and also more eyes
to look review.
בתאריך 6 בספט 2015 07:12,‏ "Paul Andrel" notifications@github.com כתב:

**Comment by AdrianLxM** [comment]
I'd also like to have the "Help the Developer" (export DB and send it to the developers) in, before a new version.
If we don't, it might take a long time (until next version + some month to collect the data).

**Comment by jstevensog** [comment]
Haven't pulled any of the last two weeks of stuff.  But otherwise it is all
good.  It worked well for two solid weeks of travel.
One thing I have noticed is that when there is heavy network (apps updated,
large chunks of data transferred, etc) BLE struggles.  Often get missed
packets during those times.  While on planes with WiFi disabled, NO missed
packets.  As soon as I am connected to WiFi, and things like apps are
updated or lots of stuff is transferred to/from the phone, dropped packets
as (I believe) the onCharacteristicChanged handler is never called.
Probably an Android thing, not an app thing, but if anyone knows how to
alter BLE priority or otherwise raise xDrip priority programatically, it
would be a great benefit IMHO.

Once the others final pieces are in, I reckon release.  Give me a heads up
so I can make the xDrip pebble watch face publicly available through the
pebble store.
Will pull and build the latest tomorrow.  Need sleep.
Cheers

On Sun, Sep 6, 2015 at 10:17 PM, AdrianLxM notifications@github.com wrote:

> I'd also like to have the "Help the Developer" (export DB and send it to
> the developers) in, before a new version.
> If we don't, it might take a long time (until next version + some month to
> collect the data).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/143#issuecomment-138078459
> .

## 

John Stevens
"You are how you live, not what you have."

**Comment by StephenBlackWasAlreadyTaken** [comment]
unless anyone objects Im going to merge this into master just to make sure we are all working with the same base code, we will try to get in the export-db and send do devs before we move it into the regular repo

**Comment by stavlor** [comment]
No objections from me i've been merging it with master locally when i do my builds for my self anyway

**Pull request merged**
