### PR TITLE
Add timeout on mongo send/receive operations.

### PR DESCRIPTION
**Pull request by tzachi-dar**
Signed-off-by: Tzachi Dar tzachi.dar@gmail.com

This is a fix for the problem of mongo upload operations that got stuck.
It seems that we have not configured timeout on the operations and as a result, this might got stuck for ever.
Verified the fix is working with much smaller timeouts.

### CODE REVIEW

**Comment by jstevensog** [comment]
I think merge away.
Nice catch Tzachi-dar.
Cheers

---- tzachi-dar wrote ----

**Comment by AdrianLxM** [comment]
Nice catch.
Before merging, could you please change the line separators.

**Comment by tzachi-dar** [comment]
Sure, I''' change the line separators.
I want to run with it for a couple of more days before merging it, so I will have more confidence in this change.

**Comment by aaroecker** [comment]
Could a time out be created for the collector?  There's a bug that's been talked about at length concerning loss of Bluetooth signal.  When the restart collector button is pushed the Bluetooth icon reappears on the Dex.  If no data is collected by the collector after six minutes a trigger could automatically restart the collector hopefully solving the issue.  Just a thought.

**Comment by jstevensog** [comment]
I have tried this in the past.  But not been successful.  Will try to revisit it soon.
Cheers

---- aaroecker wrote ----

**Comment by aaroecker** [comment]
Awesome, thank you!

**Comment by tzachi-dar** [comment]
Merged into master (not through github).

**Comment by AdrianLxM** [comment]
What did you actually change? Due to the line endings it looks like you switched the whole file.

**Comment by tzachi-dar** [comment]
Oops, only changed 2 lines, fixing that soon.

**Comment by tzachi-dar** [comment]
OK, fixed that, look at maste again.

**Pull request closed without merging**
