### PR TITLE
BG History

### PR DESCRIPTION
**Pull request by AdrianLxM**
This will add an Activity ("BG History" in the navdrawer) that shows the bg values and calibrations of a selected day (zoomable, similar to home).

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Like @tzachi-dar wished, I've added the possibility to define a range of days.

I tested it on longer and shorter days (daylight saving time adjustments) and it works fine. It will just have either one hour mark doubled (summer -> standard time) or one hour mark left out (standard -> summer time). The chart plots as it should.

**Comment by tzachi-dar** [comment]
Thanks.
בתאריך 26 בינו 2016 17:16,‏ "AdrianLxM" notifications@github.com כתב:

**Comment by tzachi-dar** [comment]
Just looked at the graphs created. Looks really nice.

I haven't still looked at the code yet.

It seems that I was not understood well. The graph that I actually need is a few days on one day graph.  This way they can see how bg behaves by the hours.

Here is an example from dexcom studio:
image

In any case, what was done here is great...

**Comment by AdrianLxM** [comment]
A couple of colleagues have tested it (thanks Barbara, RTox, Ceben, ...) and it seems to work fine on 4.4, 5.1 and 6.0.1 Android.
Before I merge it I'd still like to have a good to go from one of the core developers, so: Can I merge this?

**Comment by tzachi-dar** [comment]
I have looked at it as a user, but I still want to look at the code, so
please wait for tonight.

Thanks
Tzachi

**Comment by tzachi-dar** [comment]
OK, looked at the code. Not an expert on UI, but this seems good to me.

**Pull request merged**
