### PR TITLE
Mongo update

### PR DESCRIPTION
**Pull request by AdrianLxM**
Update mongo-java-driver to 3.0.3 (latest version) that should work with the upcoming upgrade of the free sandbox databases to version 3.0.

It seems to work on my current sandbox database (version 2.6) as for the direct upload as for the data that got queued while no data connection was possible.
-  I tested with the chrome-plugin as viewer, not nightscout/azure -> please test if you have nightscout/azure
-  Is any more update necessary to handle the actual update of the db to 3.0?

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
Nice, we will need to keep an eye on memory leaks but this should do the trick!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Merge when ready!

**Comment by AdrianLxM** [comment]
@StephenBlackWasAlreadyTaken: How soon do we need it? I'd like to test it for at least 3 consecutive days first.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Well, I would like to get the next beta update out today, so we can wait until the end of the beta and put this in before we cut it to the main version, but it might be better to have many people testing it while its beta status. I could go either way

**Comment by StephenBlackWasAlreadyTaken** [comment]
Or
we can just have a third beta update to be safe (would just include this and any other bugs that may pop up), that might be our best course of action

**Comment by AdrianLxM** [comment]
I'm definitely in favour of at least the option of a third beta update.
But with the old db-version it looks good so far - so if you want you can merge for the current beta 2.2 and when the actual test with db-version 3.0 should fail we'd have to react anyways.

**Comment by tzachi-dar** [comment]
I'll soon update one or two dexterity versions to use the latest drivers
and also an xdrip.
the xdrip will be using the wifi version that goes to the DB much more
times so I guess that in 3 days I can fake the load of 30 days of the
normal xdrip work.

This should give us a better understanding of how things are going
relatively fast.

By the way I also think that if one opens a new mogno account he will get
the 3.00 version right now. I might try that if I have time.

Thanks
Tzachi

**Comment by AdrianLxM** [comment]
worked for me until now. @tzachi-dar did a test with much heavier load -> merging

**Pull request merged**
