### PR TITLE
Just shutdown tts if it exists

### PR DESCRIPTION
**Pull request by AdrianLxM**
Shutdown TTS just/only if it exists.

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
this fixes the problem, app does not crash anymore

**Comment by AdrianLxM** [comment]
Sorry it's late: "app does not restart anymore" means it doesn't crash in the first place, I hope.

**Comment by JohanDegraeve** [comment]
correct , app does not crash anymore :+1:

**Comment by AdrianLxM** [comment]
Thanks, I will merge.

**Pull request merged**
